MeuEmprestimosLivros/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace MeuEmprestimosLivros.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Digete o nome do Recebedor!")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Digete o nome do Fornencedor!")]
        public string Fornecedor { get; set; }
        [Required(ErrorMessage = "Digete o nome do Livro empréstado!")]
        public string LivroEmprestado { get; set; }
        public DateTime DataUltimaAtualizacao { get;  set; }
    }
}

MeuEmprestimosLivros/Models/ErrorViewModel.cs
namespace MeuEmprestimosLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MeuEmprestimosLivros/Controllers/EmprestimoController.cs
using ClosedXML.Excel;
using MeuEmprestimosLivros.Data;
using MeuEmprestimosLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace MeuEmprestimosLivros.Controllers
{
    public class EmprestimoController : Controller
    {

        readonly private ApplicationDbContext _db;
        public EmprestimoController(ApplicationDbContext db)
        {
                _db = db;
        }
        public IActionResult Index()
        {
            
            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos2;


            return View(emprestimos);
        }
        [HttpGet] 
        public IActionResult Editar(int? id) 
        { 
            if (id == null || id == null)
            {
                return NotFound();
            }
            EmprestimosModel emprestimosModel = _db.Emprestimos2.FirstOrDefault(x => x.Id == id);


            if(emprestimosModel == null)
            {
                return NotFound();
            }

            return View(emprestimosModel);
        }
        [HttpGet]
        public IActionResult Excluir(int? id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            EmprestimosModel emprestimos = _db.Emprestimos2.FirstOrDefault(x => x.Id == id);

            if (emprestimos == null)
            {
                return NotFound();
            }
            return View(emprestimos);
        }

        public IActionResult Exportar()
        {
            var dados = GetDados();

            using (XLWorkbook workbook = new XLWorkbook() )
            {
                workbook.AddWorksheet(dados, "Dados Empréstimos");

                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spredsheetml.sheet", "Emprestimo.xls");
                }

            }
        }

        private DataTable GetDados()
        {
            DataTable dataTable = new DataTable();


            dataTable.TableName = "Dados empréstimos";

            dataTable.Columns.Add("Recebedor", typeof(string));
            dataTable.Columns.Add("Fornecedor", typeof (string));
            dataTable.Columns.Add("Livro", typeof(string));
            dataTable.Columns.Add("Data empréstimo", typeof(DateTime));


            var dados = _db.Emprestimos2.ToList();
            if(dados.Count > 0)
            {
                dados.ForEach(emprestimos =>
                {
                    dataTable.Rows.Add(emprestimos.Recebedor, emprestimos.Fornecedor, emprestimos.LivroEmprestado, emprestimos.DataUltimaAtualizacao);
                });
            }

            return dataTable;
        }

        [HttpGet]
        public IActionResult cadastrar()
        {
            return View();
        }
        [HttpPost]
       public IActionResult Cadastrar(EmprestimosModel emprestimos) 
        {
            if (ModelState.IsValid)
            {
                emprestimos.DataUltimaAtualizacao = DateTime.Now;

                _db.Emprestimos2.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com socesso!"; 

                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimos)
        {
            if(ModelState.IsValid)
            {
                var emprestimoDB = _db.Emprestimos2.Find(emprestimos.Id);

                emprestimoDB.Fornecedor = emprestimos.Fornecedor;
                emprestimoDB.Recebedor = emprestimos.Recebedor;
                emprestimoDB.LivroEmprestado = emprestimos.LivroEmprestado;

                _db.Emprestimos2.Update(emprestimoDB);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizado com socesso!";

                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Algum erro ocorreu ao realizar a eição!";

            return View(emprestimos);
            //teste
        }
        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimos)
        { 
            if(emprestimos == null)
            {
                return NotFound();
            }
            _db.Emprestimos2.Remove(emprestimos);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Remoção realizada com socesso!";

            return RedirectToAction("Index");

        }



    }

}

MeuEmprestimosLivros/Controllers/HomeController.cs
using MeuEmprestimosLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MeuEmprestimosLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MeuEmprestimosLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Cadastrar Emprestimos";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Empréstimos</h1>
    </div>

<form method="post" asp-controller="Emprestimo" asp-action="Cadastrar" >
    <div class="mb-3">
        <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
        <span class="text-danger" asp-validation-for="Recebedor"></span>
    </div>


    <div class="mb-3">
            <label for="Fornencedor" class="form-label text-light">Fornencedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornencedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
    </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>


    

</form>
</div>

MeuEmprestimosLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar Emprestimos";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for=Id/>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornencedor" class="form-label text-light">Fornencedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornencedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>




    </form>
</div>

MeuEmprestimosLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Excluir Emprestimos";
}

<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de Empréstimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for=Id />
        <h2 class="text-danger">Tem certeza que deseja excluir o registro abaixo?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>


        <div class="mb-3">
            <label for="Fornencedor" class="form-label text-light">Fornencedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" placeholder="Quem está emprestando o livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" placeholder="Qual é o livro que está sendo emprestado?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>




    </form>
</div>

MeuEmprestimosLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>

    <div class="container">

        <div class="d-flex justify-content-between align-intems-center mb-5">
            <h1>Empréstimos</h1>

            <div>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Exportar"><i class="bi bi-file-earmark-plus mx-2"></i>Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar novo empréstimo</a>
            </div>

        </div>


        @if(TempData["MensagemSucesso"] != null)
       {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
       }

       @if (TempData["MensagemErro"] != null)
       {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
       }

<table id="Emprestimo" class="table table-lighu table-hover mt-5">
    <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Data emprestimos</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {
            @foreach (var emprestimo in Model)
            {
                    
                <tr>
                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.DataUltimaAtualizacao</td>
                    <td>
                            <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill mx-2"></i>Excluir</a>
                    </td>
                </tr>
            }
        }


    </tbody>
</table>
</div>

MeuEmprestimosLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
    <h1 class="display-4">Empréstimos onlaine</h1>
    <p>Abra um livro, deixe-se levar. Um novo mundo você vai emcontrar!</p>
    <div>
        <img src="/img/book.png" />
    </div>

</div>

MeuEmprestimosLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meu Emprestimos Livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeuEmprestimosLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Empréstimos Tech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-journals mx-2"></i>Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container text-light">
            &copy; 2023 - MeuEmprestimosLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>